export const INDEXING_DATABASES = [
  "Google Scholar",
  "Directory of Open Access Journals (DOAJ)",
  "Crossref",
  "Scopus",
  "Indian Citation Index",
  "UGC CARE",
  "EBSCO Discovery Service",
  "ProQuest",
  "CNKI Scholar",
  "J-Gate Portal",
  "Semantic Scholar",
  "OpenAlex",
  "RePEc",
  "Zentralblatt MATH (zbMATH)",
  "Mathematical Reviews (MathSciNet)",
  "Academic Search Complete",
  "WorldCat Discovery Services",
  "Cabell's Directories",
  "DOAJ",
  "CORE",
];
